[tool.poetry]
name = "scikit-psl"
version = "0.1.0"
description = "Probabilistic Scoring List classifier"
license = "MIT"
authors = ["Stefan Heid <stefan.heid@upb.de>", "Jonas Hanselle <jonas.hanselle@ifi.lmu.de>"]
readme = "README.md"
repository = "https://github.com/stheid/scikit-psl"
packages = [
    { include = "skpsl" },]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
scikit-learn = "^1.3.0"
numpy = "^1.25.2"
scipy = "^1.11.1"
joblib = "^1.3.2"
pandas = "^2.0.3"

sphinx = { version = "^7.1", optional = true }
sphinx_rtd_theme = { version = "^1.2", optional = true  }

pytest = { version = "^7.4", optional = true }


[tool.poetry.extras]
doc = ["sphinx", "sphinx_rtd_theme"]
test = ["pytest"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"